config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :posts
  resources :comentarios
  delete "logout", to: "login#destroy"
  get "posts" => "posts#index"
  get "pagina_inicial" => "pagina_inicial#index"
  get "posts_publicos" => "posts_publico#index"
  get "posts_publicos/:id" => "posts_publico#show"
  get "/contact" => "posts_publico#contact"
  get "/about" => "posts_publico#about"
  get "/post_aleatorio" => "posts_publico#post_aleatorio"
  get "/busca" => "posts_publico#busca", as: :busca_post
  get "/todos_posts" => "posts_publico#todos"
  get "/login", to: 'login#index'
  post "/login", to: 'login#create'
  resources :posts do
    resources :comentarios
    member do
      post :hide
    end
  end
  root "login#index"
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    skip_before_action :require_login
    def create
        @usuario = Usuario.find_by(email: params[:email])
    
        if !!@usuario && @usuario.authenticate(params[:password])
            session[:usuario_id] = @usuario.id
            redirect_to pagina_inicial_url
        else
            message = "Algo deu errado! Verifique se seu email e senha estão corretos!"
            redirect_to root_url
            flash[:error] = message
        end
    end
    def destroy
        session[:usuario_id] = nil
        redirect_to root_url, notice: "Logged out"
    end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/index.html.slim
doctype html
html.loading[lang="en" data-textdirection="ltr"]
  head
    meta[http-equiv="Content-Type" content="text/html; charset=UTF-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui"]
    meta[name="description" content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities."]
    meta[name="keywords" content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app"]
    meta[name="author" content="PIXINVENT"]
    title
      | Login Page - Vuexy - Bootstrap HTML admin template
    link[rel="apple-touch-icon" href="/assets/images/ico/apple-icon-120.png"]
    link[rel="shortcut icon" type="image/x-icon" href="/assets/images/ico/favicon.ico"]
    link[href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet"]
    link[rel="stylesheet" type="text/css" href="/assets/vendors/css/vendors.min.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/bootstrap.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/bootstrap-extended.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/colors.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/components.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/themes/dark-layout.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/themes/bordered-layout.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/themes/semi-dark-layout.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/core/menu/menu-types/vertical-menu.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/plugins/forms/form-validation.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/pages/authentication.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/style.css"]
    style[type="text/css"]
       | .brand-logo:hover{ background-color:transparent!important; } 
  body.vertical-layout.vertical-menu-modern.blank-page.navbar-floating.footer-static[data-open="click" data-menu="vertical-menu-modern" data-col="blank-page"]
    .app-content.content
      .content-overlay
      .header-navbar-shadow
      .content-wrapper
        .content-header.row

        .content-body
          .auth-wrapper.auth-cover
            .auth-inner.row.m-0[style="overflow-y:clip !important"]
              = link_to root_url, class:"brand-logo"
                svg[viewbox="0 0 139 95" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="28"]
                  defs
                    lineargradient#linearGradient-1[x1="100%" y1="10.5120544%" x2="50%" y2="89.4879456%"]
                      stop[stop-color="#000000" offset="0%"]
                      stop[stop-color="#FFFFFF" offset="100%"]
                    lineargradient#linearGradient-2[x1="64.0437835%" y1="46.3276743%" x2="37.373316%" y2="100%"]
                      stop[stop-color="#EEEEEE" stop-opacity="0" offset="0%"]
                      stop[stop-color="#FFFFFF" offset="100%"]
                  g#Page-1[stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"]
                    g#Artboard[transform="translate(-400.000000, -178.000000)"]
                      g#Group[transform="translate(400.000000, 178.000000)"]
                        path#Path.text-primary[d="M-5.68434189e-14,2.84217094e-14 L39.1816085,2.84217094e-14 L69.3453773,32.2519224 L101.428699,2.84217094e-14 L138.784583,2.84217094e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L6.71554594,44.4188507 C2.46876683,39.9813776 0.345377275,35.1089553 0.345377275,29.8015838 C0.345377275,24.4942122 0.230251516,14.560351 -5.68434189e-14,2.84217094e-14 Z" style="fill: currentColor"]
                        path#Path1[d="M69.3453773,32.2519224 L101.428699,1.42108547e-14 L138.784583,1.42108547e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L32.8435758,70.5039241 L69.3453773,32.2519224 Z" fill="url(#linearGradient-1)" opacity="0.2"]
                        polygon#Path-2[fill="#000000" opacity="0.049999997" points="69.3922914 32.4202615 32.8435758 70.5039241 54.0490008 16.1851325"]
                        polygon#Path-21[fill="#000000" opacity="0.099999994" points="69.3922914 32.4202615 32.8435758 70.5039241 58.3683556 20.7402338"]
                        polygon#Path-3[fill="url(#linearGradient-2)" opacity="0.099999994" points="101.428699 0 83.0667527 94.1480575 130.378721 47.0740288"]
              h2.brand-text.text-primary.ms-1
                | Vuexy
              .d-none.d-lg-flex.col-lg-8.align-items-center.p-5
                .w-100.d-lg-flex.align-items-center.justify-content-center.px-5
                  img.img-fluid[src="/assets/images/pages/login-v2.svg" alt="Login V2"]
              .d-flex.col-lg-4.align-items-center.auth-bg.px-2.p-lg-5
                .col-12.col-sm-8.col-md-6.col-lg-12.px-xl-2.mx-auto 
                  h2.card-title.fw-bold.mb-1
                    | Welcome to Veuxy
                  = render 'shared/flashes'
                  p.card-text.mb-2
                    | Please sign-in to your account and start the adventure
                  = form_tag "/login", class:"auth-login-form mt-2" do
                    .mb-1
                      = text_field_tag :email, "", class: "form-control", placeholder:"john@example.com"
                    .mb-1
                      d-flex.justify-content-between
                        a[href="auth-forgot-password-cover.html"]
                          small
                            | Forgot Password?
                      .input-group.input-group-merge.form-password-toggle
                        = password_field_tag :password, "", class: "form-control", placeholder:"············"
                        span.input-group-text.cursor-pointer
                          i[data-feather="eye"]
                    .mb-1
                      .form-check
                        input#remember-me.form-check-input[type="checkbox" tabindex="3"]
                        label.form-check-label[for="remember-me"]
                          |  Remember Me
                    = submit_tag "Sign in", class:"btn btn-primary w-100"
                  p.text-center.mt-2
                    span
                      | New on our platform?
                    = link_to new_usuario_path
                      span
                        |  Create an account
                  .divider.my-2
                    .divider-text
                      | or
                  .auth-footer-btn.d-flex.justify-content-center
                    a.btn.btn-facebook[href="#"]
                      i[data-feather="facebook"]
                    a.btn.btn-twitter.white[href="#"]
                      i[data-feather="twitter"]
                    a.btn.btn-google[href="#"]
                      i[data-feather="mail"]
                    a.btn.btn-github[href="#"]
                      i[data-feather="github"]
    script[src="/assets/vendors/js/vendors.min.js"]
    script[src="/assets/vendors/js/forms/validation/jquery.validate.min.js"]
    script[src="/assets/js/core/app-menu.js"]
    script[src="/assets/js/core/app.js"]
    script[src="/assets/js/scripts/pages/auth-login.js"]
    script
      |  $(window).on('load', function() { if (feather) { feather.replace({ width: 14, height: 14 }); } }) 