config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :posts
  resources :comentarios
  delete "logout", to: "login#destroy"
  get "posts" => "posts#index"
  get "pagina_inicial" => "pagina_inicial#index"
  get "posts_publicos" => "posts_publico#index"
  get "posts_publicos/:id" => "posts_publico#show"
  get "/contact" => "posts_publico#contact"
  get "/about" => "posts_publico#about"
  get "/post_aleatorio" => "posts_publico#post_aleatorio"
  get "/busca" => "posts_publico#busca", as: :busca_post
  get "/todos_posts" => "posts_publico#todos"
  get "/login", to: 'login#index'
  post "/login", to: 'login#create'
  resources :posts do
    resources :comentarios
    member do
      post :hide
    end
  end
  root "login#index"
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    has_secure_password 

    validates :username, presence:true, uniqueness: true
    validates :email, presence:true,  uniqueness: true
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  skip_before_action :require_login
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
    redirect_to new_usuario_path
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
    render :new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)
    
    
    respond_to do |format|
      if @usuario.save
        session[:usuario_id] = @usuario.id
        format.html { redirect_to root_path, notice: "Usuario criado com sucesso!" }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity}
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:username, :email, :password)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.slim
= form_for @usuario do |f|
  == render 'shared/flashes'
  - invalid = @usuario.errors[:username].any?
  .form-group
    .mb-1
      = f.label :username, class:"form-label"
      = f.text_field :username, class: "form-control #{'is-invalid' if invalid}", placeholder: "johndoe"
      - if invalid
        .invalid-feedback.d-block
          - @usuario.errors[:username].each do |error|
            = error
            br
  - invalid = @usuario.errors[:email].any?
  .form-group
    .mb-1
      = f.label :email, class:"form-label"
      = f.text_field :email, class: "form-control #{'is-invalid' if invalid}", placeholder: "john@example.com"
      - if invalid
        .invalid-feedback.d-block
          - @usuario.errors[:email].each do |error|
            = error
            br
  - invalid = @usuario.errors[:password].any?
  .form-group
    .mb-1
      = f.label :password, class:"form-label"
      .input-group.input-group-merge.form-password-toggle
        = f.text_field :password, class: "form-control #{'is-invalid' if invalid}", placeholder: "*******"
        span.input-group-text.cursor-pointer
          i[data-feather="eye"]
      - if invalid
        .invalid-feedback.d-block
          - @usuario.errors[:password].each do |error|
            = error
            br 
  .mb-1
    .form-check
      input#register-privacy-policy.form-check-input[type="checkbox" tabindex="4"]
      label.form-check-label[for="register-privacy-policy"]
        | I agree to
        a[href="#"]
          |  privacy policy & terms
  = f.submit "Sign up", :class => 'btn btn-primary w-100 waves-effect waves-float waves-light'

      

app/views/usuarios/edit.html.slim
h1 Editing usuario

== render "form"

=> link_to "Show", @usuario
'|
=< link_to "Back", usuarios_path

app/views/usuarios/new.html.slim
doctype html
html.loading[lang="en" data-textdirection="ltr"]
  head
    meta[http-equiv="Content-Type" content="text/html; charset=UTF-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui"]
    meta[name="description" content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities."]
    meta[name="keywords" content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app"]
    meta[name="author" content="PIXINVENT"]
    title
      | Register Page - Vuexy - Bootstrap HTML admin template
    link[rel="apple-touch-icon" href="/assets/images/ico/apple-icon-120.png"]
    link[rel="shortcut icon" type="image/x-icon" href="/assets/images/ico/favicon.ico"]
    link[href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet"]
    link[rel="stylesheet" type="text/css" href="/assets/vendors/css/vendors.min.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/bootstrap.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/bootstrap-extended.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/colors.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/components.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/themes/dark-layout.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/themes/bordered-layout.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/themes/semi-dark-layout.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/core/menu/menu-types/vertical-menu.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/plugins/forms/form-validation.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/pages/authentication.css"]
    link[rel="stylesheet" type="text/css" href="/assets/css/style.css"]
    style[type="text/css"]
       |  .brand-logo:hover{ background-color:transparent!important; } 
  body.vertical-layout.vertical-menu-modern.blank-page.navbar-floating.footer-static[data-open="click" data-menu="vertical-menu-modern" data-col="blank-page"]
    .app-content.content
      .content-overlay
      .header-navbar-shadow
      .content-wrapper
        .content-header.row
        .content-body
          .auth-wrapper.auth-cover
            .auth-inner.row.m-0
              a.brand-logo[href="index.html"]
                svg[viewbox="0 0 139 95" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="28"]
                  defs
                    lineargradient#linearGradient-1[x1="100%" y1="10.5120544%" x2="50%" y2="89.4879456%"]
                      stop[stop-color="#000000" offset="0%"]
                      stop[stop-color="#FFFFFF" offset="100%"]
                    lineargradient#linearGradient-2[x1="64.0437835%" y1="46.3276743%" x2="37.373316%" y2="100%"]
                      stop[stop-color="#EEEEEE" stop-opacity="0" offset="0%"]
                      stop[stop-color="#FFFFFF" offset="100%"]
                  g#Page-1[stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"]
                    g#Artboard[transform="translate(-400.000000, -178.000000)"]
                      g#Group[transform="translate(400.000000, 178.000000)"]
                        path#Path.text-primary[d="M-5.68434189e-14,2.84217094e-14 L39.1816085,2.84217094e-14 L69.3453773,32.2519224 L101.428699,2.84217094e-14 L138.784583,2.84217094e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L6.71554594,44.4188507 C2.46876683,39.9813776 0.345377275,35.1089553 0.345377275,29.8015838 C0.345377275,24.4942122 0.230251516,14.560351 -5.68434189e-14,2.84217094e-14 Z" style="fill: currentColor"]
                        path#Path1[d="M69.3453773,32.2519224 L101.428699,1.42108547e-14 L138.784583,1.42108547e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L32.8435758,70.5039241 L69.3453773,32.2519224 Z" fill="url(#linearGradient-1)" opacity="0.2"]
                        polygon#Path-2[fill="#000000" opacity="0.049999997" points="69.3922914 32.4202615 32.8435758 70.5039241 54.0490008 16.1851325"]
                        polygon#Path-21[fill="#000000" opacity="0.099999994" points="69.3922914 32.4202615 32.8435758 70.5039241 58.3683556 20.7402338"]
                        polygon#Path-3[fill="url(#linearGradient-2)" opacity="0.099999994" points="101.428699 0 83.0667527 94.1480575 130.378721 47.0740288"]
              h2.brand-text.text-primary.ms-1
                | Vuexy
              .d-none.d-lg-flex.col-lg-8.align-items-center.p-5
                .w-100.d-lg-flex.align-items-center.justify-content-center.px-5
                  img.img-fluid[src="/assets/images/pages/register-v2.svg" alt="Register V2"]
              .d-flex.col-lg-4.align-items-center.auth-bg.px-2.p-lg-5
                .col-12.col-sm-8.col-md-6.col-lg-12.px-xl-2.mx-auto
                  h2.card-title.fw-bold.mb-1
                    | Adventure starts here 🚀
                  p.card-text.mb-2
                    | Make your app management easy and fun!
                  == render "form"
                  p.text-center.mt-2
                    span
                      | Already have an account?
                    = link_to root_path
                      span
                        |  Sign in instead
                  .divider.my-2
                    .divider-text
                      | or
                  .auth-footer-btn.d-flex.justify-content-center
                    a.btn.btn-facebook[href="#"]
                      i[data-feather="facebook"]
                    a.btn.btn-twitter.white[href="#"]
                      i[data-feather="twitter"]
                    a.btn.btn-google[href="#"]
                      i[data-feather="mail"]
                    a.btn.btn-github[href="#"]
                      i[data-feather="github"]
    script[src="/assets/vendors/js/vendors.min.js"]
    script[src="/assets/vendors/js/forms/validation/jquery.validate.min.js"]
    script[src="/assets/js/core/app-menu.js"]
    script[src="/assets/js/core/app.js"]
    script[src="/assets/js/scripts/pages/auth-register.js"]
    script
      |  $(window).on('load', function() { if (feather) { feather.replace({ height: 14 }); } }) 

app/views/usuarios/show.html.slim
p#notice = notice

p
  strong Username:
  = @usuario.username

p
  strong Email:
  = @usuario.email

p
  strong Password:
  = @usuario.password

=> link_to "Edit", edit_usuario_path(@usuario)
'|
=< link_to "Back", usuarios_path