config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :posts
  resources :comentarios
  delete "logout", to: "login#destroy"
  get "posts" => "posts#index"
  get "pagina_inicial" => "pagina_inicial#index"
  get "posts_publicos" => "posts_publico#index"
  get "posts_publicos/:id" => "posts_publico#show"
  get "/contact" => "posts_publico#contact"
  get "/about" => "posts_publico#about"
  get "/post_aleatorio" => "posts_publico#post_aleatorio"
  get "/busca" => "posts_publico#busca", as: :busca_post
  get "/todos_posts" => "posts_publico#todos"
  get "/login", to: 'login#index'
  post "/login", to: 'login#create'
  resources :posts do
    resources :comentarios
    member do
      post :hide
    end
  end
  root "login#index"
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comentario

    include ImageUploader::Attachment(:image)
    validates :titulo, presence:true
    validates :corpo, presence:true
    validates :image, presence:true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    layout "_layout"
    before_action :set_post, only: %i[ show edit update destroy ]

    def index
        @posts = Post.page(params[:page]).per(5)
    end

    def show
        @post.visit_counter += 1
        @post.save
    end

    def new
        @post = Post.new
        render :new
    end

    def create
        @post = Post.new(post_params)

        if @post.save
            redirect_to posts_url
            flash[:notice] = "Post salvo com sucesso"
        else
            render :new
        end
    end

    def update
        if @post.update post_params
            flash[:notice] = "Post atualizado com sucesso!"
            redirect_to posts_url
        else
            render :edit
        end
    end

    def destroy
        @post.destroy
        redirect_to posts_url
    end

    def hide
        @post = set_post
        if !@post.hidden
            @post.update_attribute(:hidden, true)
            flash[:notice] = 'Agora esse post não está mais a mostra!'
            redirect_to posts_url
        else
            @post.update_attribute(:hidden, false)
            flash[:notice] = 'Agora este post está a mostra!'
            redirect_to posts_url
        end
      end
    

    private
    def set_post
        @post = Post.find(params[:id])
      end

    def post_params
        params.require(:post).permit :titulo, :corpo, :image, :visit_counter
    end

    def increase_visit
        visit_counter+=1
        save!
    end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_form.html.slim
- @post.errors.full_messages.each do |message|
    .alert.alert-danger[role="alert"]
        = message
= form_for @post do |f|
    .mb-1
        .form-group
            = f.label :titulo
            = f.text_field :titulo, class:"form-control"
    .mb-1
        .form-group 
            = f.label :corpo
            = f.text_area :corpo, :class => "form-control tinymce", rows: 4
    .mb-1 
        .form-group 
            = f.label :image
            = f.file_field :image
    = f.submit "Criar post" , class:"btn btn-primary m-1"
    = link_to 'Back', posts_url, class: "btn btn-secondary"

app/views/posts/edit.html.slim
= render "form"

app/views/posts/index.html.slim
.col
  .card
    .card-body
      = render "shared/flashes"
      .mb-1
        = link_to "Ver página pública", posts_publicos_url
      .d-flex.justify-content-start.align-items-center.mb-1
        table.table.table-bordered
          thead
            tr
              th Título
              th Estado
              th
              th
              th
              th
          tbody
            - @posts.each do |post|
              tr
                td[style="width:50%"]
                  h5 = post.titulo
                td
                  = post.hidden ? 'Inativo' : 'Ativo'
                td
                  = button_to "Remover", post, method: :delete, class: "btn btn-danger", data: {confirm: "Tem certeza que deseja remover?"}
                td 
                  = link_to "Alterar", edit_post_path(post), class: "btn btn-secondary"
                td
                  = link_to "Ver Post", post, class: "btn btn-info"
                td
                  = button_to 'Esconder', [:hide, post], method: :post, class:"btn btn-dark", data: { confirm: "Tem certeza que deseja esconder esse post?" }
      = link_to "Criar nova postagem", new_post_path, class:"btn btn-primary"
  .d-flex.pagination
    = paginate @posts

app/views/posts/new.html.slim
= render "form"

app/views/posts/show.html.slim
.col
    .card
        .card-body
            .align-items-center.mb-1
                p 
                    | Total de visitantes nesse post: 
                    = @post.visit_counter
                .align-items-center.justify-content-center
                        h2 
                            | Post de 
                            = @current_user.username
                        .d-grid.align-items-center.justify-content-center
                            h4.d-flex.align-items-center.justify-content-center = @post.titulo
                            p.d-flex.justify-content-center = @post.corpo.html_safe
                            = image_tag @post.image_url if @post.image
            = link_to 'Edit', edit_post_path(@post), class: "btn btn-secondary"
            |                                
            = link_to 'Back', posts_url, class: "btn btn-primary"