config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :posts
  resources :comentarios
  delete "logout", to: "login#destroy"
  get "posts" => "posts#index"
  get "pagina_inicial" => "pagina_inicial#index"
  get "posts_publicos" => "posts_publico#index"
  get "posts_publicos/:id" => "posts_publico#show"
  get "/contact" => "posts_publico#contact"
  get "/about" => "posts_publico#about"
  get "/post_aleatorio" => "posts_publico#post_aleatorio"
  get "/busca" => "posts_publico#busca", as: :busca_post
  get "/todos_posts" => "posts_publico#todos"
  get "/login", to: 'login#index'
  post "/login", to: 'login#create'
  resources :posts do
    resources :comentarios
    member do
      post :hide
    end
  end
  root "login#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
    belongs_to :post
    belongs_to :parent, class_name: 'Comentario', optional: true
    has_many :replies, class_name: 'Comentario', foreign_key: :parent_id, dependent: :destroy

    validates :nome, presence:true
    validates :mensagem, presence:true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comentario

    include ImageUploader::Attachment(:image)
    validates :titulo, presence:true
    validates :corpo, presence:true
    validates :image, presence:true
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    has_secure_password 

    validates :username, presence:true, uniqueness: true
    validates :email, presence:true,  uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :info, :error, :success

private

  def require_login
    unless current_user
      redirect_to root_url
    end
  end

  def current_user
    return unless session[:usuario_id]
      @current_user ||= Usuario.find(session[:usuario_id])
  end

  def logged_in?
    !!session[:user_id]
  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
    skip_before_action :require_login
    before_action :set_comentario, only: %i[ show edit update destroy ]

    def index
        @comentarios = Comentario.all
    end

    def new
        @comentario = Comentario.new
    end
    
    def create
        @posts_publicos = Post.find(params[:post_id])
        @comentario = @posts_publicos.comentario.new(comentario_params)

        if @comentario.save
            redirect_to "/posts_publicos/#{@posts_publicos.id}"
            flash[:notice] = "Comentário criado com sucesso"
        else
            redirect_to "/posts_publicos/#{@posts_publicos.id}"
            flash[:error] = "Não foi possivel criar seu comentário!"
        end
    end

    private

    def set_comentario
        @comentario = Comentario.find(params[:id])
    end

    def comentario_params
        params.require(:comentario).permit(:post_id, :nome, :mensagem, :parent_id)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    skip_before_action :require_login
    def create
        @usuario = Usuario.find_by(email: params[:email])
    
        if !!@usuario && @usuario.authenticate(params[:password])
            session[:usuario_id] = @usuario.id
            redirect_to pagina_inicial_url
        else
            message = "Algo deu errado! Verifique se seu email e senha estão corretos!"
            redirect_to root_url
            flash[:error] = message
        end
    end
    def destroy
        session[:usuario_id] = nil
        redirect_to root_url, notice: "Logged out"
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    layout "_layout"
    before_action :set_post, only: %i[ show edit update destroy ]

    def index
        @posts = Post.page(params[:page]).per(5)
    end

    def show
        @post.visit_counter += 1
        @post.save
    end

    def new
        @post = Post.new
        render :new
    end

    def create
        @post = Post.new(post_params)

        if @post.save
            redirect_to posts_url
            flash[:notice] = "Post salvo com sucesso"
        else
            render :new
        end
    end

    def update
        if @post.update post_params
            flash[:notice] = "Post atualizado com sucesso!"
            redirect_to posts_url
        else
            render :edit
        end
    end

    def destroy
        @post.destroy
        redirect_to posts_url
    end

    def hide
        @post = set_post
        if !@post.hidden
            @post.update_attribute(:hidden, true)
            flash[:notice] = 'Agora esse post não está mais a mostra!'
            redirect_to posts_url
        else
            @post.update_attribute(:hidden, false)
            flash[:notice] = 'Agora este post está a mostra!'
            redirect_to posts_url
        end
      end
    

    private
    def set_post
        @post = Post.find(params[:id])
      end

    def post_params
        params.require(:post).permit :titulo, :corpo, :image, :visit_counter
    end

    def increase_visit
        visit_counter+=1
        save!
    end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
    def index
        @usuarios = Usuario.all
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  skip_before_action :require_login
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
    redirect_to new_usuario_path
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
    render :new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)
    
    
    respond_to do |format|
      if @usuario.save
        session[:usuario_id] = @usuario.id
        format.html { redirect_to root_path, notice: "Usuario criado com sucesso!" }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity}
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper 
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/pagina_inicial_helper.rb
module PaginaInicialHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/postagem_helper.rb
module PostagemHelper
end

app/helpers/posts_publico_helper.rb
module PostsPublicoHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/_layoutpublico.html.slim
/ | <!doctype html> 
html[lang="en"]
  head
    meta[charset="UTF-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
    meta[name="description" content=""]
    meta[name="keywords" content=""]
    meta[name="author" content=""]
    meta[name="robots" content="noindex, nofollow"]
    title
      | Travelling 
    link[rel="icon" href="http://themes.pcubelive.com/pcubeblog/favicon.ico" type="image/x-icon"]
    link[href="https://fonts.googleapis.com/css?family=Rubik:400,500,700" rel="stylesheet"]
    link[href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet"]
    link[href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet"]
    link[href="http://themes.pcubelive.com/pcubeblog/css/bootstrap.min.css" rel="stylesheet" type="text/css"]
    link[href="/assets-blog/fonts/font-awesome/font-awesome.css" rel="stylesheet" type="text/css"]
    link[href="/assets-blog/fonts/icofont/icofont.css" rel="stylesheet" type="text/css"]
    link[rel="stylesheet" href="http://themes.pcubelive.com/pcubeblog/css/owl.carousel.min.css" type="text/css"]
    link[rel="stylesheet" href="http://themes.pcubelive.com/pcubeblog/css/owl.theme.default.min.css" type="text/css"]
    link[rel="stylesheet" type="text/css" href="http://themes.pcubelive.com/pcubeblog/style.css"]
    link[rel="stylesheet" type="text/css" title="lightred" href="http://themes.pcubelive.com/pcubeblog/style.css" data-default-color="true"]
    link[rel="stylesheet" type="text/css" title="purple" href="http://themes.pcubelive.com/pcubeblog/purple.css"]
    link[rel="stylesheet" type="text/css" title="lightpurple" href="http://themes.pcubelive.com/pcubeblog/lpurple.css"]
    link[rel="stylesheet" type="text/css" title="lightsky" href="http://themes.pcubelive.com/pcubeblog/lightsky.css"]
    link[rel="stylesheet" type="text/css" title="lightgreen" href="http://themes.pcubelive.com/pcubeblog/lightgreen.css"]
    link[rel="stylesheet" type="text/css" title="lightyellow" href="http://themes.pcubelive.com/pcubeblog/lightyellow.css"]
    link[rel="stylesheet" type="text/css" title="lightblue" href="http://themes.pcubelive.com/pcubeblog/lightblue.css"]
    link[rel="stylesheet" type="text/css" title="turquoise" href="http://themes.pcubelive.com/pcubeblog/turquoise.css"]
    link[rel="stylesheet" type="text/css" title="lightgray" href="http://themes.pcubelive.com/pcubeblog/lightgray.css"]
    link[rel="stylesheet" type="text/css" title="lightorange" href="http://themes.pcubelive.com/pcubeblog/lightorange.css"]
    style[type="text/css"]
      | .pagination a{padding: 8px 12px;text-decoration: none;margin:auto; border-radius:5px}
      | .pagination a:hover{font-weight:bold;}
      | .pagination span{padding: 8px 12px;text-decoration: none;margin:auto;}
      | .pagination nav{margin:auto}
      | .current {!important;font-weight: bold;; border-radius: 5px}
  body.head_two[onload="loader()"]
    #load
      #loader
        img[src="http://themes.pcubelive.com/pcubeblog/loader.gif" alt="loader"]
    #main_div[style="display: none;"]
      .switch-color
        .icon
          i.fa.fa-paint-brush.fa-2x[style="margin-top: 7px;"]
        .box
          ul
            li
              a.colorstyle[href="#" data-switch-color="lightred" style="background-color:#eb6161;"]
            li
              a.colorstyle[href="#" data-switch-color="purple" style="background-color:#3e3951;"]
            li
              a.colorstyle[href="#" data-switch-color="lightpurple" style="background-color:#c562e0;"]
            li
              a.colorstyle[href="#" data-switch-color="lightsky" style="background-color:#32bbf6;"]
            li
              a.colorstyle[href="#" data-switch-color="lightgreen" style="background-color:#b4df40;"]
          ul
            li
              a.colorstyle[href="#" data-switch-color="lightyellow" style="background-color:#ffd015;"]
            li
              a.colorstyle[href="#" data-switch-color="lightblue" style="background-color:#2924ff;"]
            li
              a.colorstyle[href="#" data-switch-color="turquoise" style="background-color:#00e4d9;"]
            li
              a.colorstyle[href="#" data-switch-color="lightgray" style="background-color:#918f7a;"]
            li
              a.colorstyle[href="#" data-switch-color="lightorange" style="background-color:#ff781e;"]
      header.header
        .container-fluid
          .row
            .col-sm-12
              .headtop
                .col-sm-12.col-md-5.col-lg-4
                  ul.social
                    li
                      a[href="https://facebook.com" target="_blank"]
                        i.fa.fa-facebook
                    li
                      a[href="https://twitter.com" target="_blank"]
                        i.fa.fa-twitter
                    li
                      a[href="https://pinterest.com" target="_blank"]
                        i.fa.fa-pinterest-p
                    li
                      a[href="https://instagram.com" target="_blank"]
                        i.fa.fa-instagram
                    li
                      a[href="https://youtube.com" target="_blank"]
                        i.fa.fa-youtube-play
                    li
                      a[href="https://linkedin.com" target="_blank"]
                        i.fa.fa-linkedin
                .col-sm-12.col-md-3.col-lg-4.text-center
                  a[href="/posts_publicos"]
                    img[src="http://themes.pcubelive.com/pcubeblog/images/logo.png" alt="logo"]
                .col-sm-12.col-md-4.col-lg-4.text-right
                  a.sub[href="#newsletter" data-toggle="modal" title="Subscribe"]
                    i.fa.fa-envelope
                    | Email Subscribe
              .menu
                a.baricon
                  span
                    | Menu
                  i.fa.fa-bars
                ul
                  li
                    a[title="Side Menu" href="javascript:void(0);"]
                      i.fa.fa-bars.menuclick
                  li
                    a[title="Home" href="/posts_publicos"]
                      | Home
                  li
                    a[title="About" href="/about"]
                      | Sobre
                  li
                    a[title="Contact" href="/posts_publicos/#{@post_aleatorio.first.id}"]
                      | Post aleatorio
                  li
                    a[title="Contact" href="/contact"]
                      | Contato           
                  li
                    = form_tag busca_post_path, method: :get, class: 'search-form' do
                      .form-group[style="display:flex"]
                        = text_field_tag :titulo, @titulo_a_buscar, placeholder: "Busca"
                        = button_to "Buscar", nil
      aside.sidebar
        a[href="http://themes.pcubelive.com/pcubeblog/index.html"]
          img[src="http://themes.pcubelive.com/pcubeblog/images/logo.png" alt="logo"]
        a.close
          i.icofont.icofont-close-line
        ul
          li
            a[title="Home" href="/posts_publicos"]
              | Home
          li
            a[title="About" href="/about"]
              | Sobre
          li
            a[title="Contact" href="/contact"]
              | Contato  
          li
            a[title="Post Aleatório" href="/posts_publicos/#{@post_aleatorio.first.id}"]
              | Post aleatorio
        .tag_cloud[style="margin-top:1rem"]
          a.tagimg[href="#"]
            img[alt="blog" src="http://themes.pcubelive.com/pcubeblog/images/a1.jpg"]
          .carousel-caption
            i.icofont.icofont-close-line
            h5
              | Inspiration & Lifestyle Category
            a.button[href="#"]
              | More Info
      = yield
      section.articles
        .container-fluid
          .row
            .col-sm-12.text-center
              h6
                i.fa.fa-newspaper-o
                | Posts mais famosos
          .row
            .col-sm-12
              .owl-carousel.artslide
                - @posts_famosos.each do |post|
                  .item
                    .weekday
                      .excerpt_data
                        a.border[href="/posts_publicos/#{post.id}"]
                          img.img-responsive[alt="blog" src="#{post.try(:image_url)}" style="max-height: 150px"]
                        p.category_name
                          | In 
                          a[href="#"]
                            |  Business
                        h6
                          a[href="/posts_publicos/#{post.id}"]
                            = post.titulo
                        p
                          = post.try(:corpo).truncate_words(10).html_safe
                        p.category_name
                          = post.created_at 
                           | By 
                          a[href="#"]
                            |  Rodrigo
                        a.button[href="/posts_publicos/#{post.id}"]
                          | Ler mais
      .insta
        .container-fluid
          .row
            .col-sm-12.text-center
              h6
                i.fa.fa-instagram
                | Nos Siga no Instagram
        .owl-carousel.instaslide
          a.item[href="#" target="_blank"]
            img[src="http://themes.pcubelive.com/pcubeblog/images/ti1.jpg" alt="blog"]
          a.item[href="#" target="_blank"]
            img[src="http://themes.pcubelive.com/pcubeblog/images/ti2.jpg" alt="blog"]
          a.item[href="#" target="_blank"]
            img[src="http://themes.pcubelive.com/pcubeblog/images/ti3.jpg" alt="blog"]
          a.item[href="#" target="_blank"]
            img[src="http://themes.pcubelive.com/pcubeblog/images/ti4.jpg" alt="blog"]
          a.item[href="#" target="_blank"]
            img[src="http://themes.pcubelive.com/pcubeblog/images/ti5.jpg" alt="blog"]
          a.item[href="#" target="_blank"]
            img[src="/assets-blog/img/alucard.jpg" alt="blog" style="height: 358px"]
      footer.footer
        .container-fluid
          .row
            .col-sm-12.text-center
              a[href="http://themes.pcubelive.com/pcubeblog/index.html" title="Blog Site Template"]
                img[src="http://themes.pcubelive.com/pcubeblog/images/footlogo.png" alt="Logo"]
              ul.social
                li
                  a[href="https://facebook.com" target="_blank"]
                    i.fa.fa-facebook
                li
                  a[href="https://twitter.com" target="_blank"]
                    i.fa.fa-twitter
                li
                  a[href="https://pinterest.com" target="_blank"]
                    i.fa.fa-pinterest-p
                li
                  a[href="https://instagram.com" target="_blank"]
                    i.fa.fa-instagram
                li
                  a[href="https://youtube.com" target="_blank"]
                    i.fa.fa-youtube-play
                li
                  a[href="https://linkedin.com" target="_blank"]
              ul.fmenu
                li
                  a[title="Home" href="/posts_publicos"]
                    | Home
                li
                  a[title="About" href="/about"]
                    | Sobre
                li
                  a[title="Contact" href="/contact"]
                    | Contato  
                li
                  a[title="Post Aleatório" href="/posts_publicos/#{@post_aleatorio.first.id}"]
                    | Post aleatorio
      .copyright
        .container-fluid
          .row
            .col-sm-12.text-center
              p
                | Copyright © 2018 Pcube Blog Theme
      #newsletter.modal.fade
        .modal-dialog
          .modal-content
            .modal-header
              h5.modal-title
                | Join Our Newsletter
              p
                | Sign up today for free and be the first to get notified of
                br
                |  new updates
            .modal-body
              input[type="email" placeholder="Email Address"]
              input.button[type="submit" value="Subscribe Now"]
            button.close[type="button" title="close" data-dismiss="modal" aria-label="Close"]
              span[aria-hidden="true"]
                | ×
      .overlay
      a.scrollup[data-toggle="tooltip" data-placement="top" href="javascript:void(0)" title="Scroll Top"]
        i.fa.fa-angle-up
      script[src="http://themes.pcubelive.com/pcubeblog/js/jquery-3.2.1.min.js"]
      script[src="http://themes.pcubelive.com/pcubeblog/js/bootstrap.min.js"]
      script[src="http://themes.pcubelive.com/pcubeblog/js/owl.carousel.min.js"]
      script[src="http://themes.pcubelive.com/pcubeblog/js/main.js"]
      script[src="http://themes.pcubelive.com/pcubeblog/js/switch-color.js"]

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TemplateTest
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/shared/_flashes.html.slim
- if notice
  .alert.alert-info.alert-dismissible.fade.show.m-1[role="alert"]
    = notice
      span[aria-hidden="true"]
        | ×
- if error
  .alert.alert-danger.alert-dismissible.fade.show.m-1[role="alert"]
    = error
      span[aria-hidden="true"]
        | ×